server:
  port: 8082
spring:
  application:
    name: consumer
  rabbitmq:
    host: 12.0.216.200
    port: 5672
    username: int3
    password: int3
    listener:
      simple:
        acknowledge-mode: manual
    virtual-host: int3