server:
  port: 8081
spring:
  application:
    name: producer
  rabbitmq:
    host: 12.0.216.200
    port: 5672
    username: int3
    password: int3
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    virtual-host: int3