server:
  port: 8081
spring:
  application:
    name: producer
  rabbitmq:
    host: 39.107.239.107
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true